# Generated by Django 5.2.17 on 2026-09-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('ATR', 'African Traditional - Odinala/Odinani'), ('Abrahamic', 'Abrahamic'), ('Dharmic', 'Dharmic - Eastern'), ('Indigenous', 'Indigenous'), ('New', 'New Religious Movement'), ('Esoteric', 'Esoteric Tradition')], max_length=20)),
                ('origin', models.CharField(max_length=100)),
                ('founder', models.CharField(blank=True, max_length=100)),
                ('founded_date', models.CharField(blank=True, max_length=100)),
                ('followers_estimate', models.CharField(blank=True, max_length=50)),
                ('overview', models.TextField()),
                ('core_beliefs', models.TextField()),
                ('cosmology', models.TextField(blank=True)),
                ('thesis_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsotericTradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin_tradition', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inner_teaching', models.TextField()),
                ('outer_teaching', models.TextField(blank=True)),
                ('methods', models.TextField(blank=True)),
                ('parent_religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='religion.religion')),
            ],
        ),
        migrations.CreateModel(
            name='Doctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('igbo_comparison', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctrines', to='religion.religion')),
            ],
        ),
        migrations.CreateModel(
            name='Deity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('symbolism', models.TextField(blank=True)),
                ('attributes', models.TextField(blank=True)),
                ('is_alusi', models.BooleanField(default=False)),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deities', to='religion.religion')),
            ],
        ),
        migrations.CreateModel(
            name='SacredText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language_original', models.CharField(max_length=50)),
                ('language_translated', models.CharField(blank=True, max_length=100)),
                ('chapters', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('download_link', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='sacred_texts/')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='religion.religion')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='symbols/')),
                ('meaning', models.TextField()),
                ('esoteric_meaning', models.TextField(blank=True)),
                ('usage', models.TextField(blank=True)),
                ('tradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='religion.esoterictradition')),
            ],
        ),
    ]
