# Generated by Django 5.2.17 on 2026-09-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('phonological_diff', models.TextField()),
                ('lexical_diff', models.TextField(blank=True)),
                ('example_words', models.TextField()),
                ('thesis_proof', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('noun', 'Noun - Class system'), ('verb', 'Verb - Serialization, Extensor'), ('pronoun', 'Pronoun - Chi and personhood'), ('adjective', 'Adjective'), ('syntax', 'Syntax - SVO but flexible'), ('morphology', 'Morphology - Affixes')], max_length=50)),
                ('rule', models.TextField()),
                ('examples', models.TextField()),
                ('igbo_example', models.TextField()),
                ('english_gloss', models.TextField()),
                ('thesis_notes', models.TextField(blank=True)),
                ('odinala_connection', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('tone_type', models.CharField(choices=[('high', 'High - ´  ákwá egg proof'), ('low', 'Low - \\  àkwà cloth proof'), ('downstep', 'Downstep - ꜜ  ákwà cry proof'), ('rising', 'Rising - ̌  tone'), ('falling', 'Falling - ^ tone')], max_length=20)),
                ('ipa', models.CharField(max_length=20)),
                ('example1', models.CharField(max_length=100)),
                ('meaning1', models.CharField(max_length=100)),
                ('example2', models.CharField(max_length=100)),
                ('meaning2', models.CharField(max_length=100)),
                ('example3', models.CharField(blank=True, max_length=100)),
                ('meaning3', models.CharField(blank=True, max_length=100)),
                ('thesis_proof', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='tones/')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igbo', models.TextField()),
                ('ipa', models.CharField(blank=True, max_length=300)),
                ('gloss', models.TextField()),
                ('translation', models.TextField()),
                ('tone_marked', models.CharField(blank=True, max_length=300)),
                ('grammar_notes', models.TextField(blank=True)),
                ('dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language2.dialect')),
            ],
        ),
    ]
