# Generated by Django 5.1.3 on 2026-09-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="total_likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blog", "Blog 📝"),
                    ("forum", "Forum 💬 HIGH PAY"),
                    ("thread", "Thread 🧵"),
                    ("reel", "Reel 🎥"),
                    ("podcast", "Podcast 🎙️"),
                    ("poll", "Poll 📊 $0.005/vote"),
                    ("news", "News 📰 Breaking"),
                    ("market", "Marketplace 🛒 5%"),
                    ("job", "Job/Gig 💼 $2"),
                ],
                default="blog",
                max_length=20,
            ),
        ),
    ]
