# Generated by Django 5.1.3 on 2026-09-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_add_9_types_total_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="stripe_account_id",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="wise_email",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="value",
        ),
        migrations.AddField(
            model_name="vote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.post"
            ),
        ),
        migrations.AlterField(
            model_name="creatorprofile",
            name="wallet_balance_usd",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blog", "Blog"),
                    ("forum", "Forum"),
                    ("thread", "Thread"),
                    ("reel", "Reel"),
                    ("podcast", "Podcast"),
                    ("poll", "Poll"),
                    ("news", "News"),
                    ("market", "Market"),
                    ("job", "Job"),
                    ("event", "Event"),
                ],
                default="thread",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="revenue_usd",
            field=models.FloatField(default=0.0),
        ),
    ]
