# Generated by Django 5.2.17 on 2026-09-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoonCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('phase', models.CharField(max_length=20)),
                ('illumination', models.FloatField()),
                ('market_day', models.CharField(max_length=10)),
                ('farmers_note_en', models.TextField(blank=True)),
                ('fishermen_note_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
                ('name_pt', models.CharField(blank=True, max_length=100)),
                ('name_sw', models.CharField(blank=True, max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('name_ig', models.CharField(blank=True, max_length=100)),
                ('lingua_franca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('high_tide_time', models.DateTimeField()),
                ('low_tide_time', models.DateTimeField()),
                ('high_height_m', models.FloatField()),
                ('low_height_m', models.FloatField()),
                ('fishing_best', models.CharField(max_length=100)),
                ('advice_en', models.TextField(blank=True)),
                ('advice_fr', models.TextField(blank=True)),
                ('advice_sw', models.TextField(blank=True)),
                ('advice_ig', models.TextField(blank=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awag.region')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('wind_pattern', models.CharField(max_length=100)),
                ('wind_speed_kmh', models.FloatField()),
                ('wind_direction', models.CharField(max_length=20)),
                ('rainfall_mm', models.FloatField()),
                ('rainfall_prediction', models.CharField(choices=[('early', 'Early rain'), ('late', 'Late rain'), ('normal', 'Normal')], max_length=20)),
                ('soil_condition', models.CharField(choices=[('dry', 'Too dry'), ('wet', 'Too wet'), ('optimal', 'Optimal')], max_length=20)),
                ('temperature_c', models.FloatField()),
                ('humidity', models.FloatField()),
                ('forecast_reliability', models.IntegerField(default=95)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awag.region')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('farmers_planting_en', models.TextField(blank=True, verbose_name='Farmers: when to start planting')),
                ('farmers_planting_fr', models.TextField(blank=True)),
                ('farmers_planting_sw', models.TextField(blank=True)),
                ('farmers_planting_ig', models.TextField(blank=True)),
                ('farmers_harvest', models.TextField(blank=True)),
                ('farmers_sell', models.TextField(blank=True)),
                ('soil_advice', models.TextField(blank=True)),
                ('fishermen_moon_tide_en', models.TextField(blank=True, verbose_name='Fishermen: moon and tide')),
                ('fishermen_when_fish', models.TextField(blank=True)),
                ('fishermen_preserve', models.TextField(blank=True)),
                ('fishermen_sell', models.TextField(blank=True)),
                ('transporters_rain_pattern', models.TextField(blank=True)),
                ('transporters_when_move', models.TextField(blank=True)),
                ('traders_advice', models.TextField(blank=True)),
                ('artisans_advice', models.TextField(blank=True)),
                ('hunters_advice', models.TextField(blank=True)),
                ('healers_advice', models.TextField(blank=True)),
                ('leaders_advice', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('sw', 'Swahili'), ('ar', 'Arabic'), ('ig', 'Igbo')], default='en', max_length=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awag.region')),
            ],
            options={
                'verbose_name': 'AWAG - Africas Weekly Activities Guide',
                'verbose_name_plural': 'AWAG - Weekly Guides',
                'ordering': ['-week_start'],
            },
        ),
    ]
