# Generated by Django 5.2.17 on 2026-09-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='tide',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterModelOptions(
            name='weatherpattern',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='weeklyguide',
            old_name='farmers_harvest',
            new_name='farmers_planting_ar',
        ),
        migrations.RenameField(
            model_name='weeklyguide',
            old_name='farmers_sell',
            new_name='farmers_planting_es',
        ),
        migrations.RenameField(
            model_name='weeklyguide',
            old_name='soil_advice',
            new_name='farmers_planting_pt',
        ),
        migrations.AddField(
            model_name='mooncycle',
            name='farmers_note_ig',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mooncycle',
            name='fishermen_note_ig',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mooncycle',
            name='phase_symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tide',
            name='advice_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tide',
            name='advice_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tide',
            name='advice_pt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyguide',
            name='farmers_harvest_en',
            field=models.TextField(blank=True, verbose_name='When to harvest'),
        ),
        migrations.AddField(
            model_name='weeklyguide',
            name='farmers_rain_en',
            field=models.TextField(blank=True, verbose_name='Early or late rain'),
        ),
        migrations.AddField(
            model_name='weeklyguide',
            name='farmers_sell_en',
            field=models.TextField(blank=True, verbose_name='When to sell'),
        ),
        migrations.AddField(
            model_name='weeklyguide',
            name='farmers_soil_en',
            field=models.TextField(blank=True, verbose_name='Soil too dry or wet'),
        ),
        migrations.AddField(
            model_name='weeklyguide',
            name='fishermen_moon_tide_ig',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyguide',
            name='moon_phase_week',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mooncycle',
            name='illumination',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mooncycle',
            name='market_day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='lingua_franca',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('sw', 'Swahili'), ('ar', 'Arabic'), ('ig', 'Igbo')], default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='tide',
            name='fishing_best',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tide',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tides', to='awag.region'),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='humidity',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='rainfall_mm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='rainfall_prediction',
            field=models.CharField(choices=[('early', 'Early rain'), ('late', 'Late rain'), ('normal', 'Normal'), ('heavy', 'Heavy'), ('light', 'Light')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='awag.region'),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='soil_condition',
            field=models.CharField(choices=[('dry', 'Too dry'), ('wet', 'Too wet'), ('optimal', 'Optimal'), ('flooded', 'Flooded')], default='optimal', max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='temperature_c',
            field=models.FloatField(default=28),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='wind_pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherpattern',
            name='wind_speed_kmh',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyguide',
            name='farmers_planting_ig',
            field=models.TextField(blank=True, verbose_name='Ugbo: mgbe akuku'),
        ),
        migrations.AlterField(
            model_name='weeklyguide',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_guides', to='awag.region'),
        ),
    ]
