# Generated by Django 5.2.17 on 2026-09-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPhoneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('tone', 'Tone'), ('syllabic_nasal', 'Syllabic Nasal'), ('labialized', 'Labialized'), ('original', 'Original Script')], max_length=30)),
                ('ipa', models.CharField(max_length=20)),
                ('example', models.CharField(max_length=100)),
                ('meaning_diff', models.CharField(max_length=200)),
                ('reason_missing', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('ipa', models.CharField(max_length=20)),
                ('example', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('single', 'Single Letter'), ('digraph', 'Digraph - Wrongly as Letter'), ('diacritic', 'Diacritic Letter')], max_length=20)),
                ('is_dropped', models.BooleanField(default=False)),
                ('thesis_note', models.TextField(blank=True)),
            ],
        ),
    ]
