# Generated by Django 5.2.17 on 2026-09-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingphoneme',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='missing/'),
        ),
        migrations.AddField(
            model_name='presentalphabet',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='phonemes/'),
        ),
    ]
