# Generated by Django 5.2.17 on 2026-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang1', '0002_missingphoneme_audio_presentalphabet_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingphoneme',
            name='category',
            field=models.CharField(choices=[('tone', 'Tone'), ('syllabic_nasal', 'Syllabic Nasal'), ('labialized', 'Labialized - cuo, guo, kuo proof'), ('original', 'Original Script'), ('affricate_missing', 'Affricate Missing - zh, gh, tsara, azhia'), ('palatalized', 'Palatalized - zhia, ghia, nyia')], max_length=30),
        ),
        migrations.AlterField(
            model_name='presentalphabet',
            name='category',
            field=models.CharField(choices=[('single', 'Single Letter'), ('digraph', 'Digraph - Wrongly as Letter'), ('diacritic', 'Diacritic Letter'), ('labialized_consonant', 'Labialized - cuo vs chuo proof'), ('affricate', 'Affricate - ts, dz, zh, gh'), ('labialized_digraph', 'Labialized Digraph - Real Phoneme')], max_length=30),
        ),
    ]
