# Generated by Django 5.2.17 on 2026-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=20)),
                ('overview', models.TextField()),
                ('thesis_argument', models.TextField(blank=True)),
            ],
        ),
    ]
