# Generated by Django 5.1.3 on 2026-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zone", models.CharField(max_length=100)),
                ("zone_code", models.CharField(max_length=20)),
                ("wind", models.CharField(max_length=200)),
                ("rain", models.CharField(max_length=200)),
                ("tide_port", models.CharField(max_length=200)),
                ("lingua", models.CharField(default="en", max_length=10)),
                ("element", models.CharField(max_length=50)),
                ("activity", models.CharField(max_length=200)),
            ],
        ),
    ]
