# Generated by Django 5.2.17 on 2026-09-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('history', 'History - 6 pages'), ('culture', 'Culture - 5 pages'), ('language1', 'Language 1 - 5 pages'), ('lang2_app', 'Language 2 - 5 pages - SAFE'), ('religion', 'Religion - 15 pages - thesis'), ('esoterism', 'Esoterism - 7 pages'), ('tradition', 'Tradition - 5 pages'), ('biafra', 'Biafra - 5 pages'), ('slavery', 'Slavery - 5 pages'), ('nigeria', 'Nigeria - 5 pages'), ('africa', 'Africa - 5 pages'), ('pogrom', 'Pogrom - 5 pages'), ('uk', 'UK - 5 pages'), ('struggles', 'Struggles - 5 pages'), ('resistance', 'Resistance - 5 pages'), ('europe', 'Europe - 5 pages'), ('arabs', 'Arabs - 5 pages'), ('about', 'About - 5 pages'), ('people', 'People - 5 pages'), ('persons', 'Persons - 5 pages')], unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('page_count', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='e.g., history-s01', unique=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(help_text='Full HTML from PHP - as is')),
                ('content_enhanced', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='subjects.subject')),
            ],
            options={
                'ordering': ['subject', 'order'],
            },
        ),
    ]
