# Generated by Django 5.1.3 on 2026-09-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("history", "History - 6 pages"),
                    ("culture", "Culture - 5 pages"),
                    ("language1", "Language 1 - 5 pages"),
                    ("lang2_app", "Language 2 - 5 pages - SAFE"),
                    ("religion", "Religion - 15 pages - thesis"),
                    ("esoterism", "Esoterism - 7 pages"),
                    ("tradition", "Tradition - 5 pages"),
                    ("biafra", "Biafra - 5 pages"),
                    ("slavery", "Slavery - 5 pages"),
                    ("nigeria", "Nigeria - 5 pages"),
                    ("africa", "Africa - 5 pages"),
                    ("pogrom", "Pogrom - 5 pages"),
                    ("uk", "UK - 5 pages"),
                    ("struggles", "Struggles - 5 pages"),
                    ("resistance", "Resistance - 5 pages"),
                    ("europe", "Europe - 5 pages"),
                    ("arabs", "Arabs - 5 pages"),
                    ("about", "About - 5 pages"),
                    ("people", "People - 5 pages"),
                    ("persons", "Persons - 5 pages"),
                    ("spirituality", "Igbo Spirituality - 7 pages - EKE ORIE AFO NKWO"),
                ],
                unique=True,
            ),
        ),
    ]
