# Generated by Django 5.2.17 on 2026-09-14 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('religion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsotericTradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin_tradition', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inner_teaching', models.TextField()),
                ('outer_teaching', models.TextField(blank=True)),
                ('methods', models.TextField(blank=True)),
                ('parent_religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='religion.religion')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('esoteric_meaning', models.TextField(blank=True)),
                ('tradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='esoteric.esoterictradition')),
            ],
        ),
    ]
