# Generated by Django 5.2.17 on 2026-09-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmuzhiYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gregorian_year', models.IntegerField(unique=True)),
                ('igbo_year', models.IntegerField()),
                ('is_leap', models.BooleanField(default=False)),
                ('year_start_gregorian', models.DateField()),
                ('anchor_market_day', models.CharField(default='Afo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AmuzhiMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name_igbo', models.CharField(max_length=50)),
                ('gloss', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('days_in_month', models.IntegerField(default=28)),
                ('gregorian_start', models.DateField()),
                ('gregorian_end', models.DateField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='amuzhi_calendar.amuzhiyear')),
            ],
            options={
                'ordering': ['year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MarketDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_gregorian', models.DateField(db_index=True, unique=True)),
                ('market_day', models.CharField(choices=[('EKE', 'Eke'), ('ORIE', 'Orie'), ('AFO', 'Afo'), ('NKWO', 'Nkwo')], max_length=10)),
                ('igbo_day', models.IntegerField()),
                ('moon_symbol', models.CharField(blank=True, max_length=10)),
                ('moon_stage', models.CharField(blank=True, max_length=30)),
                ('illumination', models.IntegerField(default=0)),
                ('high_tide', models.TimeField(blank=True, null=True)),
                ('low_tide', models.TimeField(blank=True, null=True)),
                ('tide_height', models.FloatField(blank=True, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='amuzhi_calendar.amuzhimonth')),
            ],
            options={
                'ordering': ['date_gregorian'],
            },
        ),
    ]
