# Generated by Django 5.2.17 on 2026-09-17 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzhi_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amuzhiyear',
            options={'ordering': ['gregorian_year']},
        ),
        migrations.RenameField(
            model_name='marketday',
            old_name='tide_height',
            new_name='tide_height_m',
        ),
        migrations.AddField(
            model_name='amuzhiyear',
            name='reference_chart_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketday',
            name='is_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketday',
            name='tide_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketday',
            name='tide_location',
            field=models.CharField(blank=True, default='Bonny', max_length=100),
        ),
        migrations.AddField(
            model_name='marketday',
            name='weekday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='amuzhimonth',
            name='gloss',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='amuzhimonth',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='marketday',
            name='market_day',
            field=models.CharField(choices=[('EKE', 'Eke'), ('ORIE', 'Orie'), ('AFO', 'Afo'), ('NKWO', 'Nkwo')], db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='amuzhimonth',
            unique_together={('year', 'number')},
        ),
        migrations.CreateModel(
            name='AmuzhiTide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('high_tide', models.TimeField()),
                ('low_tide', models.TimeField()),
                ('height_m', models.FloatField()),
                ('fishing_window', models.CharField(blank=True, max_length=100)),
                ('market_effect', models.TextField(blank=True)),
                ('market_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tides', to='amuzhi_calendar.marketday')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
